import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navpage from "./layout/nav";
import { peyda } from "./lib/font";
import NoiseBackground from "./components/NoiseBackground";
import Footer from "./layout/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html dir="rtl" lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${peyda.variable} antialiased h-screen`}
      >
        <NoiseBackground />
        <div className="mx-4 md:mx-0">
          <Navpage />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
